//Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//Worker
export const GET_WORKER_PROFILE = 'GET_WORKER_PROFILE';
export const GET_WORKER_MATCHING_JOBS = 'GET_WORKER_MATCHING_JOBS';
